### ISSUE TITLE
空间不足问题

### ISSUE THREAD

**Issue by percise** [hulianyuyy/CorrNet#16]
环境是pytorch1.8.1 python 3.8.18 cuda11.1 ctcdecode0.4成功安装，但是在训练第一轮结束报了内存不足问题，服务器是A100 80g

![Uploading 1700021110772.jpg…]()
求告知大概是什么问题，看了您的其他问题说是版本问题，更换了pytorch1.13.0 也成功安装上了ctcdecode 但是在运行时也会直接报ctc的问题，麻烦给个思路 谢谢 我应该怎么去弄 是和gcc版本有问题吗 目前是11.4的gcc
或者能否告诉我你的环境是什么吗

**Comment by percise** [comment]
![1700021110772](https://github.com/hulianyuyy/CorrNet/assets/88238940/813832cd-0bf1-4eb8-82c5-e6a5dcb23803)

**Comment by hulianyuyy** [comment]
My environment is pytorch 1.10.1, ctcdecode 0.4.0, python 3.7.1, cuda 11.2. According to [other issues](https://github.com/hulianyuyy/CorrNet/issues/1#issuecomment-1489847118), you may upgrade the pytorch version to try it.

**Comment by percise** [comment]
> 我的环境是pytorch 1.10.1，ctcdecode 0.4.0，python 3.7.1，cuda 11.2。根据[其他问题](https://github.com/hulianyuyy/CorrNet/issues/1#issuecomment-1489847118)，您可以升级pytorch版本来尝试。

你好，我想请教一下 ，空间不足是不是因为内存不足导致的，我看在main.py中有个pin_memory设置为TRUE，他就一直会锁住内存，您的内存是多大呢。我现在已经改成false正在尝试了

**Comment by hulianyuyy** [comment]
I use a single 3090 GPU with 24G memory to train. But i figure that this issue is not raised by GPU memory, since your GPU has 80 GB memory.

**Comment by hulianyuyy** [comment]
Besides, you may refer to [this issue](https://github.com/parlance/ctcdecode/issues/124). This is mostly caused by ctcdecode.

**Comment by percise** [comment]
> 你可以做一些尝试。如果你仍然遇到这个问题，我将添加pythondecode，而不是ctcdecode来执行解码以摆脱这个问题。我的日程安排在11.25左右。

好的，力顶作者，为手语做出贡献！！！

**Comment by kido1412y2y** [comment]
> I use a single 3090 GPU with 24G memory to train. But i figure that this issue is not raised by GPU memory, since your GPU has 80 GB memory.

Hello, may I ask how much memory was used during training with 24GB of memory? I am using two 3060 and one 12GB of memory. Is that enough?
Because I used two GPUs, I changed here in main.py, but when I actually ran the code, the computer only used one GPU and then reported an error. Is there anything I missed? I hope to receive your reply.
![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/ae3563f9-304e-45a9-80f8-a356cfaa31c9)
![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/79ac0c6b-84d7-493c-9b8f-503e945bf85a)
![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/81417397-e789-4000-9764-30e186ce42e9)

**Comment by xxxiaosong** [comment]
Hello, I would like to ask why I use two 4090 graphics cards for training, which is much slower than using a single card.

**Comment by hulianyuyy** [comment]
Maybe you have run some code on the 4090, ans so it slows down.
