### ISSUE TITLE
Training time and logs

### ISSUE THREAD

**Issue by WANGSSSSSSS** [hulianyuyy/CorrNet#2]
Thanks for your open source spirit 🍻 , and is it possible to share the logs file for others to reproduce? And how much time does the training process consume for each dataset....

**Comment by hulianyuyy** [comment]
The log file for PHOENIX14 dataset is [here](https://drive.google.com/file/d/1VKua0xL9Uxk4fyM2XnEw4bzpsYQK9Vp7/view?usp=share_link). The training time on a single 3090 GPU for PHOENIX14, PHOENIX14-T, CSL-Daily and CSL is around 16hrs, 17hrs, 33hrs and 28hrs.

**Comment by WANGSSSSSSS** [comment]
Thks, this helps a lot! 👍🏻

**Comment by southnt** [comment]
@hulianyuyy sorry but can you check [log.txt](https://github.com/hulianyuyy/CorrNet/files/13331463/log.txt) for me? I cant get Best_dev=18.9 (PHOENIX14-T dataset) with the default setting. 

In your log, it seem the model is
'work_dir': './work_dir/baseline_res18_dist_25_corr_alpha_agg_all_r1_x2_bi_3/', in default, the model is baseline_res18

**Comment by hulianyuyy** [comment]
It seems that your configurations are right. It's worth noting that the performance varies across different machines due to cuda version, hardware or other factors. You could mostly get comparable results but not exactly 18.90. You may run it again to get another result. 'work_dir' is the log directory that saves your output files and checkpoints, while doesn't affects your training performance.
