### ISSUE TITLE
Is sclite the same as using python to evaluate?

### ISSUE THREAD

**Issue by zhenwangrs** [hulianyuyy/CorrNet#22]
Hi, may I ask could I directly using the python to evaluate rather than sclite? Will they output the same result?

**Comment by hulianyuyy** [comment]
Almost the same, within 0.1%



---Original---
From: "Zhen ***@***.***&gt;
Date: Sat, Nov 25, 2023 23:15 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [hulianyuyy/CorrNet] Is sclite the same as using python to evaluate?(Issue #22)




 
Hi, may I ask could I directly using the python to evaluate rather than sclite? Will they output the same result?

**Comment by zhenwangrs** [comment]
Got it. Thanks for your reply.
